```{r knit-setting-for-def-views, eval = TRUE, include=FALSE}
# eval but not show codes in this files
knitr::opts_chunk$set(eval = TRUE, include = FALSE)
```


```{r libraries, message=FALSE, warning=FALSE}
library("RPostgres")
library("DBI")
library("dplyr")
library("dbplyr")
```

```{r def-issue-con}
issue_con <- function(service_name) {
    # assume you are using config package and Postgres
    crd <- config::get(service_name)
    DBI::dbConnect(
        drv = RPostgres::Postgres(),
        host = crd$host,
        port = crd$port,
        dbname = crd$dbname,
        user = crd$user,
        password = crd$password
    )
}
```

```{r def-release-con}
release_cons <- function(search_from = ls(".GlobalEnv"), except = NULL) {
    purrr::map_chr(
        .x = search_from %>% base::setdiff(except),
        .f = function(x) {
            ret <- ""
            if (x %>% get() %>%
                {
                    inherits(., "PqConnection") & length(.) == 1
                }) {
                ret <- tryCatch(
                    {
                        x %>%
                            get() %>%
                            DBI::dbDisconnect()
                        return(x)
                    },
                    error = function(e) {
                        msg <- paste("Invalid PqConnection class object is provided:", x)
                        message(msg)
                    },
                    warning = function(e) {
                        return("")
                    }
                )
            }
            return(ret)
        }
    ) %>% .[. != ""]
}
```

```{r def-create-view-dbi}
dbCreateView <- function(con, name, sql, or_replace = FALSE, temporary = FALSE) {
    if (sql %>% inherits(c("character", "SQL")) %>% isFALSE()) stop("provided sql string is not of class character or SQL.")
    con %>%
        DBI::sqlInterpolate(
            sql = "CREATE ?or ?tmp VIEW ?name AS ?q",
            or = dplyr::if_else(or_replace, "OR REPLACE", "") %>% DBI::SQL(),
            tmp = dplyr::if_else(temporary, "TEMPORARY", "") %>% DBI::SQL(),
            name = DBI::dbQuoteIdentifier(., name),
            q = sql %>% DBI::SQL()
        ) %>%
        DBI::dbExecute(con, .)
    invisible(TRUE) %>% return()
}
```

```{r def-create-view-lazy}
# not included
CreateView <- function(con, tbl, name, or_replace = FALSE, temporary = FALSE) {
    if (tbl %>% base::inherits("tbl_lazy") %>% isFALSE()) stop("provided tbl is not of class tbl_lazy")
    "CREATE ?or ?tmp VIEW ?name AS ?tbl_sql" %>%
        DBI::sqlInterpolate(
            con,
            .,
            or = dplyr::if_else(or_replace, "OR REPLACE", "") %>% DBI::SQL(),
            tmp = dplyr::if_else(temporary, "TEMPORARY", "") %>% DBI::SQL(),
            name = name %>% DBI::dbQuoteIdentifier(con, .),
            tbl_sql = dbplyr::sql_render(tbl) %>% SQL()
        ) %>%
        DBI::dbExecute(con, .)
    invisible(TRUE) %>% return()
}
```

```{r def-list-views}
dbListViews <- function(con, permanent = TRUE, temporary = TRUE) {
    ret <- character()
    # this returns all views, temporary or not
    list_views <- function(x) {
        x %>%
            dbListTables() %>%
            setdiff(
                x %>%
                    DBI::dbGetQuery(
                        statement = "SELECT tablename FROM pg_tables WHERE schemaname = current_schema()"
                    ) %>% pull(1)
            )
    }
    # retruns only non-temporary views
    parm_views <- function(x) {
        x %>%
            dbGetQuery(
                statement = "SELECT viewname FROM pg_views WHERE schemaname = current_schema()"
            ) %>%
            pull(1)
    }
    # we can't use dplyr::case_when here, which requires the returned values be the same type and the same length.
    if (permanent & temporary) {
        ret <- con %>% list_views()
    } else if (permanent) {
        ret <- con %>% parm_views()
    } else if (temporary) {
        ret <- con %>%
            list_views() %>%
            setdiff(con %>% parm_views())
    }
    ret %>% return()
}
```

```{r def-exists-view}
dbExistsViews <- function(con, names, permanent = TRUE, temporary = TRUE) {
    names %in% dbListViews(con, permanent, temporary)
}
```

```{r def-drop-view}
dbDropView <- function(con, name, if_exists = FALSE, cascade = FALSE) {
    before <- con %>%
        dbListViews() %>%
        length()
    con %>%
        DBI::sqlInterpolate(
            sql = "DROP VIEW ?if_ex ?name ?cas_res",
            if_ex = dplyr::if_else(if_exists, "IF EXISTS", "") %>% DBI::SQL(),
            name = DBI::dbQuoteIdentifier(con, name),
            cas_res = dplyr::if_else(cascade, "CASCADE", "RESTRICT") %>% SQL()
        ) %>%
        DBI::dbExecute(con, .)
    before - (con %>% dbListViews() %>% length()) %>% invisible()
}
```

```{r def-drop-table}
dbDropTables <- function(conn, name, if_exists = FALSE, cascade = FALSE) {
    before <- con %>%
        dbListTables() %>%
        length()
    con %>%
        DBI::sqlInterpolate(
            sql = "DROP TABLE ?if_ex ?name ?cas_res",
            if_ex = dplyr::if_else(if_exists, "IF EXISTS", "") %>% DBI::SQL(),
            name = DBI::dbQuoteIdentifier(con, name),
            cas_res = dplyr::if_else(cascade, "CASCADE", "RESTRICT") %>% SQL()
        ) %>%
        DBI::dbExecute(con, .)
    before - (con %>% dbListTables() %>% length()) %>% invisible()
}
```

```{r def-discard-function}
dbDiscard <- function(con, all = FALSE, plans = FALSE, temporary = TRUE) {
    if (c(all, plans, temporary) %>% any()) {
        resource <- case_when(
            all ~ "ALL",
            plans ~ "PLANS",
            temporary ~ "TEMPORARY"
        )
        "DISCARD ?rsc" %>%
            DBI::sqlInterpolate(
                con,
                .,
                rsc = resource %>% DBI::SQL()
            ) %>%
            DBI::dbExecute(con, .)
    }
    invisible(TRUE) %>% return()
}
```