---
title: "Supplementary functions for DBI + RPostgres"
author: "Shena"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
github-repo: 'https://github.com/Shena4746/r-functions-on-dbi'
---

```{r knit-setting-for-top, eval = TRUE, include=FALSE}
rm(list = ls())
gc(reset = TRUE)
gc(reset = TRUE)
knitr::opts_chunk$set(eval = TRUE, echo = TRUE, warning = FALSE, collapse = TRUE)
```

# Libraries

```{r libraries, message=FALSE, warning=FALSE}
library("RPostgres")
library("DBI")
library("dplyr")
library("dbplyr")
```

This document is based on the following conditions.
```{r versions-of-libraries, collapse=TRUE}
R.version.string
packageVersion("RPostgres")
packageVersion("DBI")
packageVersion("dplyr")
packageVersion("dbplyr")
```

# Connection

```{r def-issue_con}
issue_con <- function(service_name) {
    dw <- config::get(service_name)
    con <- DBI::dbConnect(
        drv = RPostgres::Postgres(),
        host = dw$host,
        port = dw$port,
        dbname = dw$dbname,
        user = dw$user,
        password = dw$password
    )
}
```

```{r first-connection}
con <- issue_con("demo")
```